### ISSUE TITLE
Stairs Polyline object is glitchy

### ISSUE THREAD

**Issue by SourIsaac** [obrokedo/TacticalEngine#14]
Module: Planner

I may be using it wrong, but when the player walks right or left through the stairs object the player flys to the top left of the screen and back again really quickly, and does it for every step of the stairs object.

Wyndigo got it to work but the player could walk south off the stairs.

**Comment by obrokedo** [comment]
Fixed by https://github.com/obrokedo/TacticalEngine/commit/4825b296f247466e04860eb6a44e061992c7e201
