### ISSUE TITLE
Saving bug with planner

### ISSUE THREAD

**Issue by SourIsaac** [obrokedo/TacticalEngine#15]
Module: Planner

While working in the planner if you go to an existing map (erium, reyval, boldar) and make a new trigger, switch to the speech tab make a new message text item. And then go back to your trigger, and add a show speech box, saving will mess up all triggers on, conditions, search areas, npc text. and the things that get messed up seem random.

More testing might be nessessary, but im able to reproduce it every time i add new triggers to a map.

**Comment by obrokedo** [comment]
Resolved by https://github.com/obrokedo/TacticalEngine/commit/10942c2712091b4d3f7c055ed0e4226f717a2b2c
